name: DXT Explorer (Python 3.10)

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  explorer:
    runs-on: ubuntu-latest
    container: python:3.10
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Dependencies
        run: |
          git clone https://github.com/darshan-hpc/darshan.git

      - name: Build Darshan
        run: |
          export DARSHAN_DIR=/opt/darshan

          mkdir $DARSHAN_DIR
          cd darshan
          git checkout darshan-3.4.0
          bash prepare.sh
          cd darshan-util
          ./configure --prefix=$DARSHAN_DIR
          make
          make install

      - name: Install DXT Explorer
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -c darshan==3.4.0
          pip install .

      - name: Run DXT Explorer (help)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer -h

      - name: Run DXT Explorer (list)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --list sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (operation)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (transfer)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --transfer sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan 

      - name: Run DXT Explorer (spatiality)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --spatiality sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (io phase)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --io_phase sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (ost usage operation)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --ost_usage_operation sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (ost usage transfer)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --ost_usage_transfer sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (rank zero workload)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --rank_zero_workload sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (unbalanced workload)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --unbalanced_workload sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (stragglers)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --stragglers sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan
       
      - name: Run DXT Explorer (truncate runtime)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --start 3.7 sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (truncate runtime)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --end 3.9 sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan
      
      - name: Run DXT Explorer (truncate rank)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --from 1 sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan
    
      - name: Run DXT Explorer (truncate rank)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --to 100 sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Run DXT Explorer (truncate both)
        run: |
          export PATH=/opt/darshan/bin:$PATH

          dxt-explorer --debug --start 3.7 --end 3.9 --from 1 --to 100 sample/jeanbez_8_benchmark_parallel_id45195555_8-6-50011-11681279140261054765_1628283217.darshan

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: sample/**
          retention-days: 1
